/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Dialog_Copy.java
 *
 * Created on Apr 16, 2009, 7:41:29 PM
 */

package QuanLyFile;

import java.awt.Cursor;
import java.awt.Toolkit;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Administrator
 */
public class Dialog_Copy extends javax.swing.JDialog {

    BoQuanLyFile boQuanLyFile;
    Task task;
    /** Creates new form Dialog_Copy */
    public Dialog_Copy(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        boQuanLyFile = new BoQuanLyFile();
        boQuanLyFile.addPropertyChangeListener(new PropertyChangeListener() {
            public void propertyChange(PropertyChangeEvent evt) {
                if (evt.getPropertyName().equalsIgnoreCase("DangCopy")){
                    jLabel_DangCopy.setText(evt.getNewValue().toString());
                }
            }
        });
    }

    /**
     * @param jTextField_Dich the jTextField_Dich to set
     */
    public void setJTextField_Dich(javax.swing.JTextField jTextField_Dich) {
        this.jTextField_Dich = jTextField_Dich;
    }

    /**
     * @param jTextField_Nguon the jTextField_Nguon to set
     */
    public void setJTextField_Nguon(javax.swing.JTextField jTextField_Nguon) {
        this.jTextField_Nguon = jTextField_Nguon;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_Dich = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Nguon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel_DangCopy = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton_Copy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(doan_totalcommander_002.DoAn_TatalCommande_002App.class).getContext().getResourceMap(Dialog_Copy.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jTextField_Dich.setText(resourceMap.getString("jTextField_Dich.text")); // NOI18N
        jTextField_Dich.setName("jTextField_Dich"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jTextField_Nguon.setText(resourceMap.getString("jTextField_Nguon.text")); // NOI18N
        jTextField_Nguon.setName("jTextField_Nguon"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel_DangCopy.setText(resourceMap.getString("jLabel_DangCopy.text")); // NOI18N
        jLabel_DangCopy.setName("jLabel_DangCopy"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton_Copy.setText(resourceMap.getString("jButton_Copy.text")); // NOI18N
        jButton_Copy.setName("jButton_Copy"); // NOI18N
        jButton_Copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CopyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_Copy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_DangCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Nguon)
                            .addComponent(jTextField_Dich, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_Nguon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Dich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel_DangCopy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton_Copy))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Bạn muốn thoát?"
                , "Xác nhận thoát", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_CopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CopyActionPerformed
        // TODO add your handling code here:
        jButton_Copy.setEnabled(false);
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        //Instances of javax.swing.SwingWorker are not reusuable, so
        //we create new instances as needed.
        task = new Task();
        task.addPropertyChangeListener(boQuanLyFile.getPropertyChangeListeners()[0]);
        task.execute();
    }//GEN-LAST:event_jButton_CopyActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialog_Copy dialog = new Dialog_Copy(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Copy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_DangCopy;
    private javax.swing.JTextField jTextField_Dich;
    private javax.swing.JTextField jTextField_Nguon;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jTextField_Dich
     */
    public javax.swing.JTextField getJTextField_Dich() {
        return jTextField_Dich;
    }

    /**
     * @return the jTextField_Nguon
     */
    public javax.swing.JTextField getJTextField_Nguon() {
        return jTextField_Nguon;
    }    // End of variables declaration

    class Task extends SwingWorker<Void, Void> {
        public void copyFile(){
           try {
                // TODO add your handling code here:
                String str_FileNguon = getJTextField_Nguon().getText();
                String str_FileDich = getJTextField_Dich().getText();
                boQuanLyFile.copyDirectory(new File(str_FileNguon), new File(str_FileDich), false);

            } catch (IOException ex) {
                Logger.getLogger(Dialog_CatNho.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Copy file thất bại! Lỗi: " + ex.getMessage());
            }
        }
        /*
         * Main task. Executed in background thread.
         */
        @Override
        public Void doInBackground() {
            copyFile();
            return null;
        }

        /*
         * Executed in event dispatching thread
         */
        @Override
        public void done() {
            Toolkit.getDefaultToolkit().beep();
            jButton_Copy.setEnabled(true);
            setCursor(null); //turn off the wait cursor
            //jLabel_DuongDanDangTim.setText("Số file tìm được: " + jTable_TimDuoc.getRowCount());
            //Thông báo thành công và xác nhận thoát
            jLabel_DangCopy.setText("Đã hoàn thành!");
            if (JOptionPane.showConfirmDialog(null, "Copy file thành công! Bạn muốn thoát?"
                , "Xác nhận thoát", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
                dispose();

        }
    }
}
