/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Dialog_SoSanhFile.java
 *
 * Created on Apr 10, 2009, 2:59:38 AM
 */

package doan_tatalcommande_002;

import java.io.IOException;

/**
 * hiện thị dialog so sánh 2 file
 * @author Administrator
 */
public class Dialog_SoSanhFile extends javax.swing.JFrame {

    /** Creates new form Dialog_SoSanhFile */
    public Dialog_SoSanhFile() {
        initComponents();
    }
     public Dialog_SoSanhFile(String str_DuongDanFileBenTrai, String str_DuongDanFileBenPhai) throws IOException {
            initComponents();
            BoQuanLyFile.hienThiFile(str_DuongDanFileBenTrai, jTextPane_BenTrai, jEnum_CacEnumTrongBai.XemFile);
            BoQuanLyFile.hienThiFile(str_DuongDanFileBenPhai, jTextPane_BenPhai, jEnum_CacEnumTrongBai.XemFile);
        }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton_DuyetFileBenPhai = new javax.swing.JButton();
        jButton_DuyetFileBenTrai = new javax.swing.JButton();
        jButton_SoSanh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel_BenTrai = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane_BenPhai = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel_BenPhai = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane_BenTrai = new javax.swing.JTextPane();

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextPane2.setName("jTextPane2"); // NOI18N
        jScrollPane2.setViewportView(jTextPane2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(doan_tatalcommande_002.DoAn_TatalCommande_002App.class).getContext().getResourceMap(Dialog_SoSanhFile.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(680, 50));

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N

        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N

        jButton_DuyetFileBenPhai.setText(resourceMap.getString("jButton_DuyetFileBenPhai.text")); // NOI18N
        jButton_DuyetFileBenPhai.setName("jButton_DuyetFileBenPhai"); // NOI18N
        jButton_DuyetFileBenPhai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DuyetFileBenPhaiActionPerformed(evt);
            }
        });

        jButton_DuyetFileBenTrai.setText(resourceMap.getString("jButton_DuyetFileBenTrai.text")); // NOI18N
        jButton_DuyetFileBenTrai.setName("jButton_DuyetFileBenTrai"); // NOI18N
        jButton_DuyetFileBenTrai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DuyetFileBenTraiActionPerformed(evt);
            }
        });

        jButton_SoSanh.setText(resourceMap.getString("jButton_SoSanh.text")); // NOI18N
        jButton_SoSanh.setName("jButton_SoSanh"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_DuyetFileBenTrai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_SoSanh)
                .addGap(5, 5, 5)
                .addComponent(jButton_DuyetFileBenPhai, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_DuyetFileBenTrai)
                    .addComponent(jButton_DuyetFileBenPhai)
                    .addComponent(jButton_SoSanh))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setName("jPanel3"); // NOI18N

        jSplitPane1.setDividerLocation(400);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jPanel_BenTrai.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel_BenTrai.border.title"))); // NOI18N
        jPanel_BenTrai.setName("jPanel_BenTrai"); // NOI18N
        jPanel_BenTrai.setPreferredSize(new java.awt.Dimension(1000, 1000));

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        jTextPane_BenPhai.setName("jTextPane_BenPhai"); // NOI18N
        jTextPane_BenPhai.setPreferredSize(new java.awt.Dimension(1000, 500));
        jScrollPane5.setViewportView(jTextPane_BenPhai);

        javax.swing.GroupLayout jPanel_BenTraiLayout = new javax.swing.GroupLayout(jPanel_BenTrai);
        jPanel_BenTrai.setLayout(jPanel_BenTraiLayout);
        jPanel_BenTraiLayout.setHorizontalGroup(
            jPanel_BenTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 984, Short.MAX_VALUE)
            .addGroup(jPanel_BenTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_BenTraiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(356, Short.MAX_VALUE)))
        );
        jPanel_BenTraiLayout.setVerticalGroup(
            jPanel_BenTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
            .addGroup(jPanel_BenTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_BenTraiLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(579, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel_BenTrai);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jPanel_BenPhai.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel_BenPhai.border.title"))); // NOI18N
        jPanel_BenPhai.setName("jPanel_BenPhai"); // NOI18N
        jPanel_BenPhai.setPreferredSize(new java.awt.Dimension(1000, 1000));

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        jTextPane_BenTrai.setName("jTextPane_BenTrai"); // NOI18N
        jTextPane_BenTrai.setPreferredSize(new java.awt.Dimension(1000, 500));
        jScrollPane4.setViewportView(jTextPane_BenTrai);

        javax.swing.GroupLayout jPanel_BenPhaiLayout = new javax.swing.GroupLayout(jPanel_BenPhai);
        jPanel_BenPhai.setLayout(jPanel_BenPhaiLayout);
        jPanel_BenPhaiLayout.setHorizontalGroup(
            jPanel_BenPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BenPhaiLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(366, Short.MAX_VALUE))
        );
        jPanel_BenPhaiLayout.setVerticalGroup(
            jPanel_BenPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BenPhaiLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(580, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel_BenPhai);

        jSplitPane1.setRightComponent(jScrollPane3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_DuyetFileBenPhaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DuyetFileBenPhaiActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton_DuyetFileBenPhaiActionPerformed

    private void jButton_DuyetFileBenTraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DuyetFileBenTraiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton_DuyetFileBenTraiActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dialog_SoSanhFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_DuyetFileBenPhai;
    private javax.swing.JButton jButton_DuyetFileBenTrai;
    private javax.swing.JButton jButton_SoSanh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_BenPhai;
    private javax.swing.JPanel jPanel_BenTrai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane_BenPhai;
    private javax.swing.JTextPane jTextPane_BenTrai;
    // End of variables declaration//GEN-END:variables

}
